package com.yaozhitech.baobei.order.mapper;

import com.yaozhitech.baobei.order.domain.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Nov 08 18:34:25 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Nov 08 18:34:25 CST 2018
     */
    List<User> selectAll();
}